# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

allowBuilds:
    esbuild: true
    svelte-preprocess: true
    '@parcel/watcher': true

onlyBuiltDependencies:
    - svelte-preprocess
