<!--
SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)

SPDX-License-Identifier: MPL-2.0
-->
<script lang="ts">
	import BrownButton from '$lib/components/buttons/brown.svelte';
	import { goto } from '$app/navigation';
	import { premium } from '$lib/stores';
	import { onMount } from 'svelte';

	let loading = false;

	// eslint-disable-next-line no-unused-vars
	enum SubscriptionTypes {
		// eslint-disable-next-line no-unused-vars
		Annual = 'ANNUAL',
		// eslint-disable-next-line no-unused-vars
		Monthly = 'MONTHLY'
	}

	const generate_client_secret = async (type: SubscriptionTypes) => {
		if (loading) {
			return;
		}
		loading = true;
		const res = await fetch('/api/v1/users/billing/subscribe', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({
				plan: String(type)
			})
		});
		if (!res.ok) {
			alert('Something went wrong');
			loading = false;
			return;
		}
		const json = await res.json();
		await goto(
			`/account/billing/subscribe?type=${String(type)}&clientSecret=${
				json.client_secret
			}&subscription_id=${json.subscription_id}`
		);
	};
	console.log($premium);
	onMount(() => {
		console.log($premium);
	});
</script>

<div>
	<div class="mb-12">
		<h1 class="text-6xl text-center">
			<span class="marck-script text-7xl">ClassQuiz</span> Plans
		</h1>
		<div class="w-1/3 mx-auto">
			<p class="text-center">
				Paid plans... That's what nobody really likes, but I want to cover at least my
				losses generated by ClassQuiz.
			</p>
			<h2 class="text-center text-4xl m-2">Intentions</h2>
			<p>
				At first, ClassQuiz will not paywall any feature that is used by many. It limits
				resource-intensive features and it will cover some niche-features.
			</p>
			<h2 class="text-center text-4xl m-2">What ClassQuiz Free will be?</h2>
			<p class="text-center">
				ClassQuiz Free will give <b>everyone</b> the ability to host privacy-friendly, feature
				rich and engaging quizzes.
			</p>
		</div>
	</div>
	<div class="grid grid-cols-2 w-1/2 mx-auto gap-8">
		<div
			class="rounded-lg bg-white dark:bg-gray-700 p-3 shadow-2xl ring-green-600"
			class:ring-4={!$premium}
		>
			<h3 class="text-4xl text-center">
				<span class="marck-script text-5xl">ClassQuiz</span>
				<span class="italic font-bold">Free</span>
			</h3>
			<p class="text-center">Free. Forever.</p>
			<ul class="list-disc ml-3 flex flex-col gap-2">
				<li>⚠️ Only 10 results can be saved</li>
				<li>⚠️ Max. 3000 players per month</li>
				<li>✅ Cancel at any time</li>
				<li>✅ Download quizzes</li>
				<li>✅ Privacy Friendly</li>
				<li>✅ Import quizzes from Kahoot!</li>
			</ul>
			<div class="m-2">
				<BrownButton disabled={loading}>Continue for free</BrownButton>
			</div>
		</div>
		<div
			class="rounded-lg bg-white dark:bg-gray-700 p-3 shadow-2xl ring-green-600"
			class:ring-4={$premium}
		>
			<h3 class="text-4xl text-center">
				<span class="marck-script text-5xl">ClassQuiz</span>
				<span class="italic font-bold">Extended</span>
			</h3>
			<p class="text-center"><b>2</b>€/$ a month or <b>20</b>€/$ annually</p>
			<ul class="list-disc ml-3 flex flex-col gap-2">
				<li>✅ Unlimited results can be saved</li>
				<li>✅ Unlimited players per month</li>
				<li>✅ Upgrade at any time</li>
				<li>✅ Download quizzes</li>
				<li>✅ Privacy Friendly</li>
				<li>✅ Import quizzes from Kahoot!</li>
			</ul>
			<div class="flex flex-row gap-2 m-2">
				{#if $premium}
					<BrownButton>Cancel subscription</BrownButton>
				{:else}
					<BrownButton
						disabled={loading}
						on:click={() => {
							generate_client_secret(SubscriptionTypes.Annual);
						}}
					>
						{#if loading}
							Loading...
						{:else}
							Annual
						{/if}
					</BrownButton>
					<BrownButton
						disabled={loading}
						on:click={() => {
							generate_client_secret(SubscriptionTypes.Monthly);
						}}
					>
						{#if loading}
							Loading...
						{:else}
							Monthly
						{/if}
					</BrownButton>
				{/if}
			</div>
		</div>
	</div>
</div>
