"""made some changes

Revision ID: 76507db71fde
Revises: 
Create Date: 2022-02-25 18:38:08.687974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76507db71fde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
