"""Added storage_used to User

Revision ID: 01d7a503e360
Revises: 1310317108bd
Create Date: 2023-05-29 19:05:04.142548

"""
from alembic import op
import sqlalchemy as sa
import ormar
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = "01d7a503e360"
down_revision = "1310317108bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("storage_used", sa.BigInteger(), nullable=True))
    conn = op.get_bind()
    session = Session(bind=conn)
    session.execute("UPDATE users SET storage_used=0 WHERE storage_used is NULL")
    op.alter_column("users", "storage_used", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "storage_used")
    # ### end Alembic commands ###
