"""Added thumbhash and server StorageItem

Revision ID: 1310317108bd
Revises: b74382b2c6ad
Create Date: 2023-05-29 15:53:00.388788

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "1310317108bd"
down_revision = "b74382b2c6ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("storage_items", sa.Column("thumbhash", sa.Text(), nullable=True))
    op.add_column("storage_items", sa.Column("server", sa.Text(), nullable=True))
    op.add_column("storage_items", sa.Column("imported", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("storage_items", "imported")
    op.drop_column("storage_items", "server")
    op.drop_column("storage_items", "thumbhash")
    # ### end Alembic commands ###
