"""Added premium-field to user

Revision ID: 45667755e1a5
Revises: c78b67956a8f
Create Date: 2023-03-21 11:27:23.981103

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "45667755e1a5"
down_revision = "c78b67956a8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("premium", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "premium")
    # ### end Alembic commands ###
