"""Added Controllers Table

Revision ID: 4916d7b204cb
Revises: 7afe98d04169
Create Date: 2023-06-29 19:01:18.331367

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "4916d7b204cb"
down_revision = "7afe98d04169"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controller",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("user", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
        sa.Column("secret_key", sa.String(length=24), nullable=False),
        sa.Column("player_name", sa.Text(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("os_version", sa.Text(), nullable=True),
        sa.Column("wanted_os_version", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user"], ["users.id"], name="fk_controller_users_id_user"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("controller")
    # ### end Alembic commands ###
