# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

"""imported_from_kahoot field

Revision ID: 6dc09ad6f6ef
Revises: 17ea75679da8
Create Date: 2022-06-10 18:06:39.912634

"""


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6dc09ad6f6ef"
down_revision = "17ea75679da8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quiz", sa.Column("imported_from_kahoot", sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz", "imported_from_kahoot")
    # ### end Alembic commands ###
