"""Modified subscriptions table id

Revision ID: 8bb595ba99ed
Revises: d85c72a143ec
Create Date: 2023-03-21 18:12:39.735178

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "8bb595ba99ed"
down_revision = "d85c72a143ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("id", sa.CHAR(length=32), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
