# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

"""Added Mod Rating

Revision ID: 9d7fa2e6b24c
Revises: 2ed6823c69b2
Create Date: 2023-08-01 16:06:22.419662

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "9d7fa2e6b24c"
down_revision = "2ed6823c69b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quiz", sa.Column("mod_rating", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz", "mod_rating")
    # ### end Alembic commands ###
