# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

"""Added Paid Plan

Revision ID: 9ec8c57d4c06
Revises: 2ed6823c69b2
Create Date: 2023-07-24 22:32:19.501070

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "9ec8c57d4c06"
down_revision = "2ed6823c69b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.Text(), nullable=False),
        sa.Column("user", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("subscription_status", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Enum("ANNUAL", "MONTHLY", name="subscriptionplans"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user"], ["users.id"], name="fk_subscriptions_users_id_user"),
        sa.PrimaryKeyConstraint("subscription_id"),
    )
    op.add_column("users", sa.Column("stripe_id", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("premium", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "premium")
    op.drop_column("users", "stripe_id")
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
