"""Added subscriptions table

Revision ID: b3cae72fcf87
Revises: 45667755e1a5
Create Date: 2023-03-21 17:35:30.774113

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "b3cae72fcf87"
down_revision = "45667755e1a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # op.execute("CREATE TYPE subscriptionplans AS ENUM ('ANNUAL', 'MONTHLY');")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscriptions",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("user", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("subscription_id", sa.Text(), nullable=False),
        sa.Column("subscription_status", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Enum("ANNUAL", "MONTHLY", name="subscriptionplans"), nullable=False),
        sa.ForeignKeyConstraint(["user"], ["users.id"], name="fk_subscriptions_users_id_user"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscriptions")
    # ### end Alembic commands ###
    # op.execute("DROP TYPE IF EXISTS subscriptionplans;")
