"""Added controllers table

Revision ID: b9ca06dfa179
Revises: 7afe98d04169
Create Date: 2023-04-03 13:16:49.585163

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "b9ca06dfa179"
down_revision = "7afe98d04169"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controllers",
        sa.Column("id", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
        sa.Column("user", ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
        sa.Column("secret_key", sa.String(length=24), nullable=False),
        sa.Column("player_name", sa.Text(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("os_version", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user"], ["users.id"], name="fk_controllers_users_id_user"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("controllers")
    # ### end Alembic commands ###
