"""Added stripe_id to user

Revision ID: c78b67956a8f
Revises: 7afe98d04169
Create Date: 2023-03-20 21:29:58.677285

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "c78b67956a8f"
down_revision = "7afe98d04169"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("stripe_id", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "stripe_id")
    # ### end Alembic commands ###
