# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

"""added cover_image

Revision ID: cda6903dfc0c
Revises: 3f63c0130bce
Create Date: 2022-09-08 16:40:01.675020

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "cda6903dfc0c"
down_revision = "3f63c0130bce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "instance_data", ["instance_id"])
    op.add_column("quiz", sa.Column("cover_image", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz", "cover_image")
    # ### end Alembic commands ###
