"""Modified subscriptions tabel

Revision ID: d85c72a143ec
Revises: b3cae72fcf87
Create Date: 2023-03-21 18:01:53.273657

"""
from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "d85c72a143ec"
down_revision = "b3cae72fcf87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("subscriptions", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "updated_at")
    op.drop_column("subscriptions", "created_at")
    # ### end Alembic commands ###
