# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

"""added github_oauth

Revision ID: da778d551bf4
Revises: 0c081a52ab8a
Create Date: 2022-06-11 16:41:35.761391

"""


from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision = "da778d551bf4"
down_revision = "0c081a52ab8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userauthtypes ADD VALUE 'GITHUB';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userauthtypes DROP VALUE 'GITHUB';")
    # ### end Alembic commands ###
